version: "3.8"

networks:
  transpong-network:
    name: transpong-network
    driver: bridge

services:
  database:
    container_name: transpong-database
    hostname: transdb_host
    image: postgres:15 # lastest on 2023-05-13
    init: true
    restart: always
    env_file: 
      - ./srcs/front_end/.env.local
      - ./srcs/back_end/src/config/env/.development.env
    volumes:
      - ./volumes/db/data:/var/lib/postgresql/data
    networks:
      - transpong-network
  
  nginx:
    image: nginx:latest 
    restart: always 
    container_name: transpong-nginx 
    ports: 
      - 8080:80
    volumes: 
      - ./srcs/nginx/conf:/etc/nginx/conf.d:ro
    networks: 
      - transpong-network

  frontend:
    container_name: front-end
    hostname: transfe_host
    build: ./srcs/front_end
    init: true
    restart: always
    env_file: 
      - ./srcs/front_end/.env.local
      - ./srcs/back_end/src/config/env/.development.env
    volumes:
      - ./srcs/front_end:/transpong
    # ports: 
    #   - 4000:4000
    networks:
      - transpong-network
    depends_on:
      - backend

  backend:
    container_name: back-end
    hostname: transbe_host
    build: ./srcs/back_end
    init: true
    restart: always
    env_file: 
      - ./srcs/front_end/.env.local
      - ./srcs/back_end/src/config/env/.development.env
    volumes: 
      - ./srcs/back_end:/transpong
    # ports: 
    #   - 3000:3000
    networks:
      - transpong-network