version: "3.9"

<<<<<<< HEAD
services:
 db:
  image: mysql:5.7
  volumes:
   - db_data:/var/lib/mysql
  restart: always
  environment:
   MYSQL_ROOT_PASSWORD: somewordpress
   MYSQL_DATABASE: wordpress
   MYSQL_USER: wordpress
   MYSQL_PASSWORD: wordpress

 wordpress:
  depends_on:
   - db
  image: wordpress:latest
  volumes:
   - wordpress_data:/var/www/html
  ports:
   - "8000:80"
  restart: always
  environment:
   WORDPRESS_DB_HOST: db
   WORDPRESS_DB_USER: wordpress
   WORDPRESS_DB_PASSWORD: wordpress
   WORDPRESS_DB_NAME: wordpress
volumes:
 db_data: {}
 wordpress_data: {}
=======
volumes:
 data: {}
services:
 mariadb:
  image: debian:buster
  restart: always
  expose:
   - "3306"
  networks:
   - intra
  tty: true
 nginx:
  image: debian:buster
  restart: always
  ports:
   - "443:443"
  volumes:
   - data:/var/www/html
  networks:
   - intra
  tty: true
 wordpress:
  image: debian:buster
  restart: always
  volumes:
   - data:/var/www/html
  expose:
   - "9000"
  networks:
   - intra
  tty: true
networks:
 intra:
  driver: bridge
>>>>>>> 406e8d4 ([ENV] setting upload)
