version: "3"

services:
  mariadb:
    container_name: "mariadb"
    build: ./requirements/mariadb/
    restart: always
    volumes:
      - ${VOLPATH}/mariadb/:/var/lib/mysql/
    expose:
      - "3306"
    networks:
      - intra
    tty: true

  nginx:
    container_name: "nginx"
    build: ./requirements/nginx/
    restart: always
    ports:
      - "443:443"
    volumes:
      - ${VOLPATH}/wordpress:/var/www/wordpress
    networks:
      - intra
    tty: true

  wordpress:
    container_name: "wordpress"
    build: ./requirements/wordpress/
    restart: always
    volumes:
      - ${VOLPATH}/wordpress:/var/www/wordpress
    expose:
      - "9000"
    networks:
      - intra
    depends_on:
      - "mariadb"
    tty: true

networks:
  intra:
    driver: bridge

volumes:
  volume-mariadb:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: ${VOLPATH}/mariadb
      
  volume-wordpress:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: ${VOLPATH}/wordpress